"""Add posted_at to Content model

Revision ID: 23f7c4ad05a5
Revises: 825a05ef218c
Create Date: 2025-10-03 07:31:26.947567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f7c4ad05a5'
down_revision = '825a05ef218c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('posted_at')

    # ### end Alembic commands ###
