"""Add scheduled_time to content

Revision ID: 825a05ef218c
Revises: 
Create Date: 2025-10-03 07:16:54.411724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825a05ef218c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('scheduled_time')

    # ### end Alembic commands ###
